name:                PFAD
version:             0.1.0.0
github:              "waddlaw/PFAD"
author:              "Shinya Yamguchi"
copyright:           "2019 Shinya Yamguchi"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/waddlaw/PFAD#readme>

dependencies:
- base >= 4.7 && < 5
- array

library:
  source-dirs: src

executables:
  minfree:
    main: app/Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - PFAD
  fastMinfree:
    main: app/FastMinfreeApp.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - PFAD

tests:
  PFAD-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - PFAD
    - hspec
    - QuickCheck
  PFAD-doctest:
    main: test/doctests.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - PFAD
    - doctest
  PFAD-tasty:
    main: Tasty.hs
    source-dirs: test-tasty
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - PFAD
    - tasty
    - tasty-hunit
    - tasty-quickcheck
    - tasty-hspec
    - hspec
    - tasty-expected-failure
    - tasty-golden

benchmarks:
  criterion:
    main: bench/Criterion.hs
    dependencies:
    - criterion
    - PFAD
  gauge:
    main: bench/Gauge.hs
    dependencies:
    - gauge
    - PFAD
