name: stack

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04
    container: quay.io/haskell_works/stack-build-icu
    steps:
    - uses: actions/checkout@v1

    - name: Display stack version
      run: stack --version

    - name: Build & test
      run: |
        stack install tasty-discover
        stack test --fast --stack-root $HOME --allow-different-user
